# Generated by Django 5.1.1 on 2024-11-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceID', models.IntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('Class_note', 'Class_note'), ('Faculty_info', 'Faculty_info'), ('University_info', 'University_info'), ('Rules_regulations', 'Rules_regulations'), ('Custom', 'Custom')], max_length=300, null=True)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.user')),
            ],
        ),
    ]
