# Generated by Django 5.1.1 on 2024-11-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_remove_clubmember_userid_remove_comment_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postId',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentId',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='resourceID',
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ClubMember',
        ),
    ]
