# Generated by Django 5.1.1 on 2024-11-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_rename_postid_comment_post_remove_comment_commentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
