# Generated by Django 5.1.1 on 2024-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_rename_media_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
