# Generated by Django 5.1.1 on 2024-11-23 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
