# Generated by Django 5.1.1 on 2024-12-03 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0019_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='forum_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='forum_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
