# Generated by Django 5.1.1 on 2024-12-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0020_forum_downvotes_forum_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
