# Generated by Django 5.2 on 2025-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0021_alter_resources_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('current_location', models.CharField(max_length=100)),
                ('current_job', models.CharField(max_length=100)),
            ],
        ),
    ]
